# Generated by Django 5.2.7 on 2025-11-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
